#!/usr/bin/env node
// build-edge.js — 读取 dist/ 编译产物，生成 edge-functions/[[default]].js

const fs = require("fs");
const path = require("path");

const distDir = path.join(__dirname, "dist");

// 读取所有静态文件
const staticFiles = {};

function walkDir(dir) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    const rel = "/" + path.relative(distDir, full);
    if (entry.isDirectory()) {
      walkDir(full);
    } else {
      staticFiles[rel] = fs.readFileSync(full, "utf-8");
    }
  }
}
walkDir(distDir);

// 生成 static map（用 JSON，更安全）
const staticMapJSON = JSON.stringify(staticFiles);

// MIME types
const mimeTypes = {
  ".html": "text/html; charset=utf-8",
  ".js": "application/javascript; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".svg": "image/svg+xml",
  ".json": "application/json; charset=utf-8",
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".ico": "image/x-icon",
  ".woff2": "font/woff2",
  ".woff": "font/woff",
};

// 生成 edge function
const edgeCode = `// Auto-generated by build-edge.js — DO NOT EDIT
const STATIC_FILES = ${staticMapJSON};

const CORS = {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Methods":"GET,POST,PUT,DELETE,OPTIONS","Access-Control-Allow-Headers":"Content-Type"};

function getMimeType(p) {
  const ext = p.slice(p.lastIndexOf("."));
  return {".html":"text/html; charset=utf-8",".js":"application/javascript; charset=utf-8",".css":"text/css; charset=utf-8",".svg":"image/svg+xml",".json":"application/json",".png":"image/png",".jpg":"image/jpeg",".ico":"image/x-icon",".woff2":"font/woff2",".woff":"font/woff"}[ext] || "application/octet-stream";
}

async function handleApi(context) {
  const {request} = context;
  const url = new URL(request.url);
  const path = url.pathname;
  const kv = TEXTDB;

  if (request.method === "OPTIONS") return new Response(null, {status:204, headers:CORS});

  // POST /update/
  if (path === "/update/" || path === "/update") {
    if (request.method !== "POST") {
      return new Response(JSON.stringify({status:0,error:"请使用 POST 方法"}), {status:405, headers:{...CORS,"Content-Type":"application/json"}});
    }
    const ct = (request.headers.get("content-type")||"").toLowerCase();
    let params = {};
    try {
      if (ct.includes("json")) params = await request.json();
      else if (ct.includes("form")) { const fd = await request.formData(); params = Object.fromEntries(fd.entries()); }
    } catch(e) {}
    const key = (params.key||"").trim();
    const value = params.value;
    if (!/^[0-9a-zA-Z_]{1,512}$/.test(key)) {
      return new Response(JSON.stringify({status:0,error:"key 格式错误"}), {status:400, headers:{...CORS,"Content-Type":"application/json"}});
    }
    if (value === "" || value === undefined || value === null) {
      await kv.delete(key);
      return new Response(JSON.stringify({status:1,data:{key,url:url.origin+"/"+key,action:"deleted"},req_id:Math.random().toString(36).slice(2,18)}), {headers:{...CORS,"Content-Type":"application/json"}});
    }
    if (typeof value !== "string" || value.length > 200000) {
      return new Response(JSON.stringify({status:0,error:"value 不能为空且不能超过 20 万字符"}), {status:400, headers:{...CORS,"Content-Type":"application/json"}});
    }
    await kv.put(key, value);
    return new Response(JSON.stringify({status:1,data:{key,url:url.origin+"/"+key},req_id:Math.random().toString(36).slice(2,18)}), {headers:{...CORS,"Content-Type":"application/json"}});
  }

  // GET /{key}
  if (request.method === "GET") {
    const key = path.slice(1);
    if (!/^[0-9a-zA-Z_]{1,512}$/.test(key)) {
      return new Response("", {headers:{...CORS,"Content-Type":"text/plain"}});
    }
    const val = await kv.get(key);
    return new Response(val || "", {headers:{...CORS,"Content-Type":"text/plain; charset=utf-8"}});
  }

  // POST /{key}
  if (request.method === "POST") {
    const key = path.slice(1);
    if (!/^[0-9a-zA-Z_]{1,512}$/.test(key)) {
      return new Response(JSON.stringify({status:0,error:"key 格式错误"}), {status:400, headers:{...CORS,"Content-Type":"application/json"}});
    }
    const ct = (request.headers.get("content-type")||"").toLowerCase();
    let value = ct.includes("json") ? await request.json().then(b => typeof b==="string"?b:JSON.stringify(b)) : await request.text();
    if (!value) { await kv.delete(key); return new Response(JSON.stringify({status:1,data:{key,action:"deleted"},req_id:Math.random().toString(36).slice(2,18)}), {headers:{...CORS,"Content-Type":"application/json"}}); }
    if (value.length > 200000) return new Response(JSON.stringify({status:0,error:"value 不能超过 20 万字符"}), {status:400, headers:{...CORS,"Content-Type":"application/json"}});
    await kv.put(key, value);
    return new Response(JSON.stringify({status:1,data:{key,url:url.origin+"/"+key},req_id:Math.random().toString(36).slice(2,18)}), {headers:{...CORS,"Content-Type":"application/json"}});
  }

  // DELETE /{key}
  if (request.method === "DELETE") {
    const key = path.slice(1);
    if (!/^[0-9a-zA-Z_]{1,512}$/.test(key)) {
      return new Response(JSON.stringify({status:0,error:"key 格式错误"}), {status:400, headers:{...CORS,"Content-Type":"application/json"}});
    }
    await kv.delete(key);
    return new Response(JSON.stringify({status:1,data:{key,action:"deleted"},req_id:Math.random().toString(36).slice(2,18)}), {headers:{...CORS,"Content-Type":"application/json"}});
  }

  return new Response(JSON.stringify({status:0,error:"不支持的请求方式"}), {status:405, headers:{...CORS,"Content-Type":"application/json"}});
}

export default function onRequest(context) {
  const url = new URL(context.request.url);
  const path = url.pathname;

  // Static files
  if (path === "/" || path === "/index.html") {
    const html = STATIC_FILES["/index.html"];
    if (html) return new Response(html, {headers:{"Content-Type":"text/html; charset=utf-8",...CORS}});
  }
  if (STATIC_FILES[path]) {
    return new Response(STATIC_FILES[path], {headers:{"Content-Type":getMimeType(path),...CORS}});
  }

  // API routes
  return handleApi(context);
}
`;

fs.writeFileSync(path.join(__dirname, "edge-functions/[[default]].js"), edgeCode);
console.log(`✅ Generated edge-functions/[[default]].js (${Object.keys(staticFiles).length} static files, ${edgeCode.length} bytes)`);
