#!/usr/bin/env node
// build-edge.cjs — 读取 dist/ 编译产物，生成符合 EdgeOne Pages 标准的 edge-functions/[[default]].js

const fs = require("fs");
const path = require("path");

const distDir = path.join(__dirname, "dist");

// 读取所有静态文件
const staticFiles = {};

function walkDir(dir) {
  if (!fs.existsSync(dir)) return;
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    const rel = "/" + path.relative(distDir, full);
    if (entry.isDirectory()) {
      walkDir(full);
    } else {
      // 排除一些不需要的大文件或源码
      if (entry.name.endsWith(".map")) continue;
      staticFiles[rel] = fs.readFileSync(full, "utf-8");
    }
  }
}
walkDir(distDir);

const staticMapJSON = JSON.stringify(staticFiles);

const edgeCode = `// Auto-generated by build-edge.cjs — DO NOT EDIT
const STATIC_FILES = \${staticMapJSON};
const CORS = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Methods": "GET,POST,PUT,DELETE,OPTIONS",
  "Access-Control-Allow-Headers": "Content-Type"
};

function getMimeType(p) {
  const ext = p.slice(p.lastIndexOf(".")).toLowerCase();
  const types = {
    ".html": "text/html; charset=utf-8",
    ".js": "application/javascript; charset=utf-8",
    ".css": "text/css; charset=utf-8",
    ".svg": "image/svg+xml",
    ".json": "application/json",
    ".png": "image/png",
    ".jpg": "image/jpeg",
    ".ico": "image/x-icon"
  };
  return types[ext] || "application/octet-stream";
}

async function handleApi(context) {
  const { request, env } = context;
  const url = new URL(request.url);
  const path = url.pathname;
  
  // 按照官方文档，从 env 中获取 KV 绑定
  const kv = (env && env.TEXTDB) || (typeof TEXTDB !== 'undefined' ? TEXTDB : null);

  if (request.method === "OPTIONS") return new Response(null, {status: 204, headers: CORS});

  if (!kv) {
    return new Response(JSON.stringify({
      status: 0, 
      error: "KV namespace 'TEXTDB' is not bound. Please bind your KV to 'TEXTDB' in EdgeOne Pages settings."
    }), {status: 500, headers: {...CORS, "Content-Type": "application/json"}});
  }

  // 路由分发
  try {
    // 写入/更新接口: POST /update/ 或 POST /{key}
    if ((path === "/update/" || path === "/update" || path.length > 1) && request.method === "POST") {
      let key, value;
      const ct = (request.headers.get("content-type") || "").toLowerCase();
      
      if (path === "/update/" || path === "/update") {
        let params = {};
        if (ct.includes("json")) params = await request.json();
        else {
          const fd = await request.formData();
          params = Object.fromEntries(fd.entries());
        }
        key = (params.key || "").trim();
        value = params.value;
      } else {
        key = path.slice(1);
        value = ct.includes("json") ? await request.json().then(v => typeof v === 'string' ? v : JSON.stringify(v)) : await request.text();
      }

      if (!/^[0-9a-zA-Z_]{1,512}$/.test(key)) {
        return new Response(JSON.stringify({status:0, error:"Invalid Key format"}), {status:400, headers: {...CORS, "Content-Type":"application/json"}});
      }

      if (value === undefined || value === null || value === "") {
        await kv.delete(key);
        return new Response(JSON.stringify({status:1, data:{key, action:"deleted"}}), {headers: {...CORS, "Content-Type":"application/json"}});
      }

      await kv.put(key, value);
      return new Response(JSON.stringify({status:1, data:{key, url: url.origin + "/" + key}}), {headers: {...CORS, "Content-Type":"application/json"}});
    }

    // 读取接口: GET /{key}
    if (request.method === "GET" && path.length > 1) {
      const key = path.slice(1);
      if (/^[0-9a-zA-Z_]{1,512}$/.test(key)) {
        const val = await kv.get(key);
        return new Response(val || "", {headers: {...CORS, "Content-Type": "text/plain; charset=utf-8"}});
      }
    }

    // 删除接口: DELETE /{key}
    if (request.method === "DELETE" && path.length > 1) {
      const key = path.slice(1);
      await kv.delete(key);
      return new Response(JSON.stringify({status:1, data:{key, action:"deleted"}}), {headers: {...CORS, "Content-Type":"application/json"}});
    }

    return new Response(JSON.stringify({status:0, error:"Endpoint not found or method not allowed"}), {status:404, headers: {...CORS, "Content-Type":"application/json"}});
  } catch (e) {
    return new Response(JSON.stringify({status:0, error: e.message, stack: e.stack}), {status:500, headers: {...CORS, "Content-Type":"application/json"}});
  }
}

// EdgeOne Pages 官方推荐导出方式
export async function onRequest(context) {
  const { request } = context;
  const url = new URL(request.url);
  const path = url.pathname;

  // 静态文件处理
  if (path === "/" || path === "/index.html") {
    return new Response(STATIC_FILES["/index.html"], {headers: {"Content-Type": "text/html; charset=utf-8", ...CORS}});
  }
  
  if (STATIC_FILES[path]) {
    return new Response(STATIC_FILES[path], {headers: {"Content-Type": getMimeType(path), ...CORS}});
  }

  // API 路由处理
  return handleApi(context);
}
`;

const outputDir = path.join(__dirname, "edge-functions");
if (!fs.existsSync(outputDir)) fs.mkdirSync(outputDir);
fs.writeFileSync(path.join(outputDir, "[[default]].js"), edgeCode);

console.log("✅ Refactored edge-functions/[[default]].js based on official documentation.");
