#!/usr/bin/env node
const fs = require("fs");
const path = require("path");

const distDir = path.join(__dirname, "dist");
const functionsDir = path.join(__dirname, "functions");
if (!fs.existsSync(functionsDir)) fs.mkdirSync(functionsDir);

const staticFiles = {};
function walkDir(dir) {
  if (!fs.existsSync(dir)) return;
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    const rel = "/" + path.relative(distDir, full);
    if (entry.isDirectory()) walkDir(full);
    else if (!entry.name.endsWith(".map")) {
      staticFiles[rel] = fs.readFileSync(full, "utf-8");
    }
  }
}
walkDir(distDir);

const staticMapJSON = JSON.stringify(staticFiles);

const lines = [
  "// Auto-generated by build-edge.cjs",
  "const STATIC_FILES = " + staticMapJSON + ";",
  "const CORS = {",
  "  'Access-Control-Allow-Origin': '*',",
  "  'Access-Control-Allow-Methods': 'GET,POST,PUT,DELETE,OPTIONS',",
  "  'Access-Control-Allow-Headers': 'Content-Type'",
  "};",
  "",
  "const HTML_SECURITY_HEADERS = {",
  "  'Content-Type': 'text/html; charset=utf-8',",
  "  'X-Content-Type-Options': 'nosniff',",
  "  'Content-Security-Policy': \"default-src 'self'; script-src 'unsafe-inline' 'self'; object-src 'none'; style-src 'unsafe-inline' 'self'; img-src 'self' data: https:; font-src 'self' https:; connect-src 'none'; form-action 'none'; base-uri 'self'; frame-ancestors 'self'\",",
  "};",
  "",
  "function getMimeType(p) {",
  "  const ext = p.slice(p.lastIndexOf('.')).toLowerCase();",
  "  const types = {",
  "    '.html': 'text/html; charset=utf-8', '.js': 'application/javascript',",
  "    '.css': 'text/css', '.svg': 'image/svg+xml', '.json': 'application/json',",
  "    '.png': 'image/png', '.jpg': 'image/jpeg', '.ico': 'image/x-icon'",
  "  };",
  "  return types[ext] || 'application/octet-stream';",
  "}",
  "",
  "async function handleApi(context) {",
  "  const { request } = context;",
  "  const url = new URL(request.url);",
  "  const path = url.pathname;",
  "  // 按官方文档：直接使用全局变量 TEXTDB",
  "",
  "  if (request.method === 'OPTIONS') return new Response(null, {status: 204, headers: CORS});",
  "",
  "  try {",
  "    if (request.method === 'POST') {",
  "      let key, value;",
  "      const ct = (request.headers.get('content-type') || '').toLowerCase();",
  "      if (path === '/update/' || path === '/update' || path === '/api/update') {",
  "        let params = {};",
  "        if (ct.includes('json')) params = await request.json();",
  "        else {",
  "          const fd = await request.formData();",
  "          params = Object.fromEntries(fd.entries());",
  "        }",
  "        key = (params.key || '').trim();",
  "        value = params.value;",
  "      } else {",
  "        key = path.split('/').pop();",
  "        value = ct.includes('json') ? await request.json().then(v => typeof v === 'string' ? v : JSON.stringify(v)) : await request.text();",
  "      }",
  "      if (!key || !/^[0-9a-zA-Z_]{1,512}$/.test(key)) return new Response(JSON.stringify({status:0, error:'Invalid Key'}), {status:400, headers: {...CORS, 'Content-Type':'application/json'}});",
  "      if (!value) {",
  "        await TEXTDB.delete(key);",
  "        return new Response(JSON.stringify({status:1, data:{key, action:'deleted'}}), {headers: {...CORS, 'Content-Type':'application/json'}});",
  "      }",
  "      const MAX_VALUE_SIZE = 5 * 1024 * 1024; // 5 MiB（实测 KV 单值上限 5,242,880 B）",
  "      const valueStr = typeof value === 'string' ? value : JSON.stringify(value);",
  "      if (valueStr.length > MAX_VALUE_SIZE) {",
  "        return new Response(JSON.stringify({status:0, error:'Value too large (max 5 MiB)'}), {status:413, headers: {...CORS, 'Content-Type':'application/json'}});",
  "      }",
  "      await TEXTDB.put(key, value);",
  "      return new Response(JSON.stringify({status:1, data:{key, url: url.origin + '/' + key}}), {headers: {...CORS, 'Content-Type':'application/json'}});",
  "    }",
  "    if (request.method === 'GET') {",
  "      const key = path.split('/').pop();",
  "      if (key && /^[0-9a-zA-Z_]{1,512}$/.test(key)) {",
  "        const val = await TEXTDB.get(key);",
  "        return new Response(val || '', {headers: {...CORS, 'Content-Type': 'text/plain; charset=utf-8'}});",
  "      }",
  "    }",
  "    if (request.method === 'DELETE') {",
  "      const key = path.split('/').pop();",
  "      await TEXTDB.delete(key);",
  "      return new Response(JSON.stringify({status:1, data:{key, action:'deleted'}}), {headers: {...CORS, 'Content-Type':'application/json'}});",
  "    }",
  "    return new Response(JSON.stringify({status:0, error:'Not Found'}), {status:404, headers: {...CORS, 'Content-Type':'application/json'}});",
  "  } catch (e) {",
  "    return new Response(JSON.stringify({status:0, error: e.message}), {status:500, headers: {...CORS, 'Content-Type':'application/json'}});",
  "  }",
  "}",
  "",
  "export async function onRequest(context) {",
  "  const { request } = context;",
  "  const url = new URL(request.url);",
  "  const path = url.pathname;",
  "",
  "  // OPTIONS 预检（所有路径）",
  "  if (request.method === 'OPTIONS') return new Response(null, {status: 204, headers: CORS});",
  "",
  "  // HTML 渲染路由 /p/{key}",
  "  if (request.method === 'GET' && path.startsWith('/p/')) {",
  "    const key = path.slice(3);",
  "    if (key && /^[0-9a-zA-Z_]{1,512}$/.test(key)) {",
  "      const val = await TEXTDB.get(key);",
  "      if (val === null) {",
  "        return new Response('Not Found', {status: 404, headers: CORS});",
  "      }",
  "      return new Response(val, {headers: {...HTML_SECURITY_HEADERS, ...CORS}});",
  "    }",
  "    return new Response('Invalid Key', {status: 400, headers: CORS});",
  "  }",
  "",
  "  // JavaScript 路由 /js/{key} — 返回 application/javascript",
  "  if (request.method === 'GET' && path.startsWith('/js/')) {",
  "    const key = path.slice(4);",
  "    if (key && /^[0-9a-zA-Z_]{1,512}$/.test(key)) {",
  "      const val = await TEXTDB.get(key);",
  "      if (val === null) {",
  "        return new Response('Not Found', {status: 404, headers: CORS});",
  "      }",
  "      return new Response(val, {headers: {...CORS, 'Content-Type': 'application/javascript; charset=utf-8'}});",
  "    }",
  "    return new Response('Invalid Key', {status: 400, headers: CORS});",
  "  }",
  "",
  "  // Markdown 渲染路由 /md/{key} — 返回 SPA，前端自行解析渲染",
  "  if (request.method === 'GET' && path.startsWith('/md/')) {",
  "    const key = path.slice(4);",
  "    if (key && /^[0-9a-zA-Z_]{1,512}$/.test(key)) {",
  "      return new Response(STATIC_FILES['/index.html'], {",
  "        headers: {'Content-Type': 'text/html; charset=utf-8', ...CORS}",
  "      });",
  "    }",
  "    return new Response('Invalid Key', {status: 400, headers: CORS});",
  "  }",
  "",
  "  // KV 测试路由",
  "  if (path === '/test-kv' || path === '/test-kv/') {",
  "    try {",
  "      // 按官方文档：直接使用全局变量 TEXTDB",
  "      const val = await TEXTDB.get('test_key');",
  "      let count = Number(val || '0') + 1;",
  "      await TEXTDB.put('test_key', String(count));",
  "      return new Response(JSON.stringify({status:'ok', count:count, message:'KV works!'}), {headers:{'Content-Type':'application/json', ...CORS}});",
  "    } catch (e) {",
  "      return new Response(JSON.stringify({status:'error', error:e.message, stack:e.stack}), {status:500, headers:{'Content-Type':'application/json'}});",
  "    }",
  "  }",
  "",
  "  if (path === '/' || path === '/index.html') {",
  "    return new Response(STATIC_FILES['/index.html'], {headers: {'Content-Type': 'text/html; charset=utf-8', ...CORS}});",
  "  }",
  "  if (STATIC_FILES[path]) {",
  "    return new Response(STATIC_FILES[path], {headers: {'Content-Type': getMimeType(path), ...CORS}});",
  "  }",
  "  return handleApi(context);",
  "}"
];

const edgeCode = lines.join("\n");
fs.writeFileSync(path.join(functionsDir, "[[default]].js"), edgeCode);
const apiSubDir = path.join(functionsDir, "api");
if (!fs.existsSync(apiSubDir)) fs.mkdirSync(apiSubDir);
fs.writeFileSync(path.join(apiSubDir, "[[default]].js"), edgeCode);

const edgeDir = path.join(__dirname, "edge-functions");
if (!fs.existsSync(edgeDir)) fs.mkdirSync(edgeDir);
fs.writeFileSync(path.join(edgeDir, "[[default]].js"), edgeCode);

console.log("✅ build-edge.cjs fixed with safe join.");
