// Auto-generated by build-edge.cjs
const STATIC_FILES = ${staticMapJSON};
const CORS = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Methods": "GET,POST,PUT,DELETE,OPTIONS",
  "Access-Control-Allow-Headers": "Content-Type"
};

function getMimeType(p) {
  const ext = p.slice(p.lastIndexOf(".")).toLowerCase();
  const types = {
    ".html": "text/html; charset=utf-8", ".js": "application/javascript", 
    ".css": "text/css", ".svg": "image/svg+xml", ".json": "application/json",
    ".png": "image/png", ".jpg": "image/jpeg", ".ico": "image/x-icon"
  };
  return types[ext] || "application/octet-stream";
}

// 核心业务处理
async function handleApi(context) {
  const { request, env } = context;
  const url = new URL(request.url);
  const path = url.pathname;
  
  // 【关键】官方文档明确：通过 env.变量名 获取 KV 实例
  // 你配置的变量名是 TEXTDB，对应的命名空间是 textdb
  const kv = (env && env.TEXTDB) ? env.TEXTDB : (typeof TEXTDB !== 'undefined' ? TEXTDB : null);

  if (request.method === "OPTIONS") return new Response(null, {status: 204, headers: CORS});

  if (!kv) {
    return new Response(JSON.stringify({
      status: 0, 
      error: "KV 'TEXTDB' is not bound correctly. Please check EdgeOne Pages settings."
    }), {status: 500, headers: {...CORS, "Content-Type": "application/json"}});
  }

  try {
    // 写入/更新: POST /update/ 或 POST /{key}
    if (request.method === "POST") {
      let key, value;
      const ct = (request.headers.get("content-type") || "").toLowerCase();
      
      if (path === "/update/" || path === "/update") {
        let params = {};
        if (ct.includes("json")) params = await request.json();
        else {
          const fd = await request.formData();
          params = Object.fromEntries(fd.entries());
        }
        key = (params.key || "").trim();
        value = params.value;
      } else {
        key = path.slice(1);
        value = ct.includes("json") ? await request.json().then(v => typeof v === 'string' ? v : JSON.stringify(v)) : await request.text();
      }

      if (!/^[0-9a-zA-Z_]{1,512}$/.test(key)) {
        return new Response(JSON.stringify({status:0, error:"Invalid Key"}), {status:400, headers: {...CORS, "Content-Type":"application/json"}});
      }

      if (value === undefined || value === null || value === "") {
        await kv.delete(key);
        return new Response(JSON.stringify({status:1, data:{key, action:"deleted"}}), {headers: {...CORS, "Content-Type":"application/json"}});
      }

      // 【官方规范】await kv.put(key, value)
      await kv.put(key, value);
      return new Response(JSON.stringify({status:1, data:{key, url: url.origin + "/" + key}}), {headers: {...CORS, "Content-Type":"application/json"}});
    }

    // 读取: GET /{key}
    if (request.method === "GET" && path.length > 1) {
      const key = path.slice(1);
      if (/^[0-9a-zA-Z_]{1,512}$/.test(key)) {
        // 【官方规范】await kv.get(key)
        const val = await kv.get(key);
        return new Response(val || "", {headers: {...CORS, "Content-Type": "text/plain; charset=utf-8"}});
      }
    }

    // 删除: DELETE /{key}
    if (request.method === "DELETE" && path.length > 1) {
      const key = path.slice(1);
      await kv.delete(key);
      return new Response(JSON.stringify({status:1, data:{key, action:"deleted"}}), {headers: {...CORS, "Content-Type":"application/json"}});
    }

    return new Response(JSON.stringify({status:0, error:"Not Found"}), {status:404, headers: {...CORS, "Content-Type":"application/json"}});
  } catch (e) {
    return new Response(JSON.stringify({status:0, error: e.message}), {status:500, headers: {...CORS, "Content-Type":"application/json"}});
  }
}

// 导出官方入口
export async function onRequest(context) {
  const { request } = context;
  const url = new URL(request.url);
  const path = url.pathname;

  if (path === "/" || path === "/index.html") {
    return new Response(STATIC_FILES["/index.html"], {headers: {"Content-Type": "text/html; charset=utf-8", ...CORS}});
  }
  
  if (STATIC_FILES[path]) {
    return new Response(STATIC_FILES[path], {headers: {"Content-Type": getMimeType(path), ...CORS}});
  }

  return handleApi(context);
}
